
server:
  port: 80

naver-cloud-sms:
  senderPhone: ''
  serviceId: ''
  accessKey: ''
  secretKey: ''

spring:
  application:
    name: springboot-shop
  redis:
    host: 127.0.0.1
    port: 6379

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  ####################################
  # MySQL Setting
  ####################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pip?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  ####################################
  # JPA Setting
  ####################################
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update      # create, update, validate, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true          # SQL
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace